### ISSUE TITLE
Issue in extensions?

### ISSUE THREAD

**Issue by ghost** [aperezdc/webkit2gtk-python-webextension-example#4]
When calling request.get_http_headers() from webpage.connect("send-request", on_send_request) callback, current loading is killed. Is the issue in this module or in WebKit python bindings?

**Comment by aperezdc** [comment]
@gnumdk: Hi there! Thanks for reporting the issue. I would suspect that the issue is in the GObject-Introspection annotations (which are used by the Python bindings). A couple of questions:

- Which version of WebKitGTK+ are you using?
- Does the the crash happen always, or only ocassionally?

I'll try to check this a bit to find the root cause of the problem.

**Comment by ghost** [comment]
WebKitGTK+ 2.16.1
Happen always.

**Comment by ghost** [comment]
It's fixed by this patch: https://bugzilla.gnome.org/show_bug.cgi?id=731501
